### ISSUE TITLE
Request: Chart snapshot

### ISSUE THREAD

**Issue by NAZARETH64** [vsnz/TradingView-Webhook-Bot#23]
Hi, tradingview have snapshot feature (alt+s or click camera on the top right corner).
It would be very amazing if bot could autosnapshot chart after alert pops-op, and paste the image url on the message

reference: 
https://www.tradingview.com/support/solutions/43000482537-how-do-i-take-a-snapshot-and-share-it-afterwards/
https://stackoverflow.com/questions/55063639/automatically-take-snapshots-of-tradingview-charts-and-save-in-google-docs

hopefully it's not that complex to work, and thanks once again for such amazing project!

**Comment by vsnz** [comment]
Hi,

Since the Image URL is not included in TradingViews Webhook feed its not a really tangible implementation right now. At least I am not aware of it being supported. 

You could technically implement it by using [Beautiful Soup](https://pypi.org/project/beautifulsoup4/) but that's not something I am interested in adding.
